// Auto-generated during build process.

#ifndef STATE_LABELS_H
#define STATE_LABELS_H

#define ST_LVL_PLAYER_UP 0
#define ST_LVL_PLAYER_DOWN 4
#define ST_LVL_PLAYER_RIGHT 8
#define ST_LVL_PLAYER_TAP 12
#define ST_LVL_PLAYER_CRUSH 15
#define ST_LVL_PLAYER_BURN 20
#define ST_LVL_PLAYER_PUSH_RIGHT 31
#define ST_LVL_PLAYER_EXIT 36
#define ST_LVL_DIG_V 44
#define ST_LVL_DIG_H 48
#define ST_LVL_SPARK 52
#define ST_LVL_EXPLODE 64
#define ST_LVL_ROCK 71
#define ST_LVL_ROCK_ROLL 72
#define ST_LVL_GOLD 76
#define ST_LVL_GOLD_ROLL 77
#define ST_LVL_GOLD_TAKE 81
#define ST_LVL_DIAMOND 84
#define ST_LVL_DIAMOND_ROLL 85
#define ST_LVL_DIAMOND_TAKE 89
#define ST_LVL_TNT_TAKE 92
#define ST_LVL_TNT 94
#define ST_LVL_GHOST_RIGHT 106
#define ST_LVL_GHOST_UP 108
#define ST_LVL_GHOST_DOWN 110

#endif
