// Auto-generated during build process.

#ifndef STATE_LABELS_H
#define STATE_LABELS_H

#define ST_LVL_PLAYER_UP 0
#define ST_LVL_PLAYER_DOWN 8
#define ST_LVL_PLAYER_RIGHT 16
#define ST_LVL_PLAYER_TAP 24
#define ST_LVL_PLAYER_CRUSH 27
#define ST_LVL_PLAYER_BURN 31
#define ST_LVL_PLAYER_PUSH_RIGHT 41
#define ST_LVL_PLAYER_EXIT 43
#define ST_LVL_DIG_V 51
#define ST_LVL_DIG_H 55
#define ST_LVL_SPARK 59
#define ST_LVL_EXPLODE 71
#define ST_LVL_ROCK 78
#define ST_LVL_ROCK_ROLL 79
#define ST_LVL_GOLD 83
#define ST_LVL_GOLD_ROLL 84
#define ST_LVL_GOLD_TAKE 88
#define ST_LVL_DIAMOND 91
#define ST_LVL_DIAMOND_ROLL 92
#define ST_LVL_DIAMOND_TAKE 96

#endif
